# Generated by Django 4.1.1 on 2022-09-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio', '0002_delete_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='file/audio')),
            ],
        ),
    ]
