# Generated by Django 4.1.1 on 2022-09-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_alter_audio_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
