# Generated by Django 4.1.1 on 2022-09-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_remove_audio_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to='file/audio'),
        ),
    ]
