# Generated by Django 4.1.1 on 2022-09-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0009_alter_audio_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to='audio'),
        ),
    ]
