# Generated by Django 4.1.1 on 2024-06-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="video")),
                (
                    "poster_url",
                    models.TextField(default="poster/video/default.jpg", max_length=50),
                ),
                ("name", models.TextField(max_length=40)),
                ("size", models.FloatField()),
            ],
        ),
    ]
