# Generated by Django 4.1.1 on 2022-09-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_rename_video_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='size',
            field=models.FloatField(default=5.01),
            preserve_default=False,
        ),
    ]
