# Generated by Django 4.1.1 on 2022-09-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Video',
            new_name='video',
        ),
    ]
